# version: '3.8'
# services:
#   client:
#     build: ./client
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=production

#   server:
#     build: ./server
#     ports:
#       - "8000:8000"
#     environment:
#       - NODE_ENV=production

#   valkey:
#     image: valkey/valkey
#     ports:
#       - "6379:6379"

#   qdrant:
#     image: qdrant/qdrant
#     ports:
#       - "6333:6333"

version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - QDRANT_URL=http://qdrant:6333
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - valkey
      - qdrant

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    command: ["--save", "60", "1"]

  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  valkey-data:
  qdrant-data: