import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedOut,
  SignedIn,
  UserButton,
} from "@clerk/nextjs";
import Authenticating from "@/components/Authenticating";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SignedOut>
            <div className="flex flex-col items-center justify-center min-h-screen p-4 bg-gray-900">
              <h1 className="mb-8 text-3xl font-extrabold text-white">
                PDF AI Assistant
              </h1>
              <Authenticating />
            </div>
          </SignedOut>
          <SignedIn>
            <div className="flex flex-col items-centre justify-centre min-h-screen p-4 bg-gray-900">
              <div className="flex items-center justify-end w-full">
                <UserButton />
              </div>
              {children}
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
